try:
    result=4/2
except:
    print('error happened')
finally:
    print('finally here')
print('Done')